import type {
  IntelligenceEvent,
  AirdropOpportunity,
  Alert,
  WatchlistItem,
  SourceInfo,
  MarketMover,
  MacroEvent,
  SystemStatus,
  UserSettings,
} from './types'

const now = new Date()
const mins = (m: number) => new Date(now.getTime() - m * 60000).toISOString()
const hrs = (h: number) => new Date(now.getTime() - h * 3600000).toISOString()

export const demoEvents: IntelligenceEvent[] = [
  { id: 'evt-001', event_id: 'EVT-FED-2026-0824-001', headline: 'Fed Chair Signals Potential Rate Cut in September Meeting', summary: 'Federal Reserve Chair indicated the committee is prepared to adjust policy stance if labor market conditions continue to soften, markets now pricing 78% probability of a 25bp cut.', detail: 'In a carefully worded statement following the Jackson Hole symposium, the Fed Chair noted that the balance of risks to our dual mandate has shifted.', asset: 'USD', asset_class: 'MACRO', category: 'official', source: 'Federal Reserve', source_url: 'https://federalreserve.gov/newsevents', source_type: 'central_bank', source_credibility: 98, published_at: mins(12), detected_at: mins(10), confidence_score: 96, impact_score: 94, direction: 'MIXED', verification_status: 'OFFICIAL', affected_assets: ['BTC', 'ETH', 'Gold', 'USD', 'Nasdaq', 'S&P 500', 'US10Y'], reasoning: 'Fed dovish pivot historically supports risk assets and weakens USD.', market_reaction: 'BTC +3.2%, Gold +1.8%, USDIndex -0.6%, Nasdaq futures +1.1%, 10Y yield -8bps', agent_type: 'macro', is_demo: true, source_count: 14, other_sources: [{ name: 'Reuters', url: 'https://reuters.com' }, { name: 'Bloomberg', url: 'https://bloomberg.com' }, { name: 'CNBC', url: 'https://cnbc.com' }], },
  { id: 'evt-002', event_id: 'EVT-CRYPTO-2026-0824-001', headline: 'Bitcoin Breaks Above $120,000 Resistance', summary: 'BTC surged past the key $120K resistance level following Fed dovish signals, with $2.4B in liquidations in the past hour.', asset: 'BTC', asset_class: 'CRYPTO', category: 'market_reaction', source: 'CoinGlass', source_url: 'https://coinglass.com', source_type: 'crypto_media', source_credibility: 85, published_at: mins(8), detected_at: mins(6), confidence_score: 92, impact_score: 88, direction: 'BULLISH', verification_status: 'CONFIRMED', affected_assets: ['BTC', 'ETH', 'SOL', 'Altcoins'], reasoning: 'Breaking a major resistance level with high volume suggests strong momentum.', market_reaction: 'BTC +4.1% in 30min, ETH +3.8%, SOL +5.2%', agent_type: 'crypto', is_demo: true, source_count: 8 },
  { id: 'evt-003', event_id: 'EVT-GEO-2026-0824-001', headline: 'EU Announces New Sanctions Package Targeting Russian Energy Exports', summary: 'European Commission proposed a 15th sanctions package targeting remaining Russian oil and LNG exports.', asset: 'Oil', asset_class: 'GEOPOLITICAL', category: 'official', source: 'European Commission', source_url: 'https://ec.europa.eu', source_type: 'government', source_credibility: 95, published_at: mins(45), detected_at: mins(40), confidence_score: 88, impact_score: 76, direction: 'BULLISH', verification_status: 'OFFICIAL', affected_assets: ['Brent', 'WTI', 'Natural Gas', 'EUR', 'RUB'], agent_type: 'geopolitical', is_demo: true, source_count: 6 },
  { id: 'evt-004', event_id: 'EVT-FOREX-2026-0824-001', headline: 'Japan GDP Q2 Revised Upward', summary: 'Japan Q2 GDP revised to +2.4% annualized, strengthening case for BOJ to raise rates at October meeting.', asset: 'USD/JPY', asset_class: 'FOREX', category: 'confirmed', source: 'Cabinet Office, Japan', source_url: 'https://www.cao.go.jp', source_type: 'government', source_credibility: 95, published_at: hrs(2), detected_at: hrs(1.5), confidence_score: 90, impact_score: 68, direction: 'BEARISH', verification_status: 'CONFIRMED', affected_assets: ['USD/JPY', 'JPY', 'Nikkei', 'JP10Y'], agent_type: 'forex', is_demo: true, source_count: 5 },
  { id: 'evt-005', event_id: 'EVT-STOCKS-2026-0824-001', headline: 'NVIDIA Reports Q2 Revenue of $52B', summary: 'NVIDIA posted record quarterly revenue of $52B, driven by unprecedented AI infrastructure demand.', asset: 'NVDA', asset_class: 'STOCKS', category: 'official', source: 'NVIDIA Corporation', source_url: 'https://nvidia.com/en-us/investor/', source_type: 'official', source_credibility: 98, published_at: hrs(3), detected_at: hrs(2.8), confidence_score: 98, impact_score: 82, direction: 'BULLISH', verification_status: 'OFFICIAL', affected_assets: ['NVDA', 'AMD', 'AVGO', 'SMCI', 'Nasdaq'], agent_type: 'stocks', is_demo: true, source_count: 3 },
  { id: 'evt-006', event_id: 'EVT-CRYPTO-2026-0824-002', headline: 'Ethereum ETF Sees Record $1.2B Daily Inflow', summary: 'US spot Ethereum ETFs recorded combined net inflows of $1.2B, the highest single-day figure since launch.', asset: 'ETH', asset_class: 'CRYPTO', category: 'confirmed', source: 'Bloomberg Intelligence', source_url: 'https://bloomberg.com/professional', source_type: 'financial_media', source_credibility: 90, published_at: mins(90), detected_at: mins(80), confidence_score: 88, impact_score: 78, direction: 'BULLISH', verification_status: 'CONFIRMED', affected_assets: ['ETH', 'ETH Staking', 'L2 Tokens', 'DeFi'], agent_type: 'crypto', is_demo: true, source_count: 4 },
  { id: 'evt-007', event_id: 'EVT-CRYPTO-2026-0824-003', headline: 'RUMOR: Major Exchange Considering XRP Delisting', summary: 'Unverified reports suggest a top-3 exchange may delist XRP due to ongoing regulatory pressure.', asset: 'XRP', asset_class: 'CRYPTO', category: 'rumor', source: 'Crypto Twitter', source_url: 'https://x.com', source_type: 'social', source_credibility: 25, published_at: mins(30), detected_at: mins(25), confidence_score: 18, impact_score: 45, direction: 'BEARISH', verification_status: 'RUMOR', affected_assets: ['XRP'], reasoning: 'Delisting from a major exchange would reduce liquidity.', risk_flags: ['Unverified source', 'Social media origin', 'No official confirmation'], agent_type: 'crypto', is_demo: true, source_count: 1 },
  { id: 'evt-008', event_id: 'EVT-COMMODITY-2026-0824-001', headline: 'OPEC+ Emergency Meeting Called', summary: 'OPEC+ has called an emergency meeting for Thursday to discuss potential production cuts of 1.5M bpd.', asset: 'Brent', asset_class: 'COMMODITIES', category: 'confirmed', source: 'Reuters', source_url: 'https://reuters.com/business/energy', source_type: 'financial_media', source_credibility: 88, published_at: hrs(1), detected_at: mins(50), confidence_score: 75, impact_score: 72, direction: 'BULLISH', verification_status: 'CONFIRMED', affected_assets: ['Brent', 'WTI', 'Energy Stocks', 'CAD', 'NOK'], agent_type: 'commodities', is_demo: true, source_count: 3 },
  { id: 'evt-009', event_id: 'EVT-MACRO-2026-0824-001', headline: 'US CPI Comes in Hot at 3.8% YoY', summary: 'US August CPI rose 3.8% year-over-year vs 3.5% expected, with core CPI at 3.9%.', asset: 'USD', asset_class: 'MACRO', category: 'official', source: 'Bureau of Labor Statistics', source_url: 'https://bls.gov/cpi', source_type: 'government', source_credibility: 98, published_at: hrs(4), detected_at: hrs(3.8), confidence_score: 98, impact_score: 85, direction: 'MIXED', verification_status: 'OFFICIAL', affected_assets: ['USD', 'US10Y', 'BTC', 'Gold', 'Nasdaq'], agent_type: 'macro', is_demo: true, source_count: 12 },
  { id: 'evt-010', event_id: 'EVT-CRYPTO-2026-0824-004', headline: 'Solana Mobile Chapter 2 Preorders Exceed 500K Units', summary: 'Solana Mobile announced that Chapter 2 preorders have surpassed 500K units.', asset: 'SOL', asset_class: 'CRYPTO', category: 'confirmed', source: 'Solana Foundation', source_url: 'https://solana.com/news', source_type: 'official', source_credibility: 85, published_at: hrs(5), detected_at: hrs(4.5), confidence_score: 82, impact_score: 55, direction: 'BULLISH', verification_status: 'CONFIRMED', affected_assets: ['SOL', 'SOL Mobile'], agent_type: 'crypto', is_demo: true, source_count: 2 },
  { id: 'evt-011', event_id: 'EVT-CRYPTO-2026-0824-005', headline: 'Potential Smart Contract Vulnerability Found in DeFi Protocol', summary: 'Security researchers identified a potential reentrancy vulnerability in a major DeFi lending protocol. $350M TVL at risk.', asset: 'DeFi', asset_class: 'CRYPTO', category: 'confirmed', source: 'SlowMist Security', source_url: 'https://slowmist.com', source_type: 'crypto_media', source_credibility: 82, published_at: mins(15), detected_at: mins(12), confidence_score: 72, impact_score: 81, direction: 'BEARISH', verification_status: 'CONFIRMED', affected_assets: ['DeFi', 'ETH'], risk_flags: ['Smart contract risk', 'Potential fund loss', 'DeFi contagion risk'], agent_type: 'crypto', is_demo: true, source_count: 2 },
  { id: 'evt-012', event_id: 'EVT-STOCKS-2026-0824-002', headline: 'Apple Announces $110B Share Buyback', summary: 'Apple authorized a new $110B share repurchase program and increased quarterly dividend by 4%.', asset: 'AAPL', asset_class: 'STOCKS', category: 'official', source: 'Apple Inc.', source_url: 'https://investor.apple.com', source_type: 'official', source_credibility: 98, published_at: hrs(6), detected_at: hrs(5.5), confidence_score: 98, impact_score: 65, direction: 'BULLISH', verification_status: 'OFFICIAL', affected_assets: ['AAPL', 'Nasdaq', 'S&P 500', 'Tech Sector'], agent_type: 'stocks', is_demo: true, source_count: 2 },
]

export const demoAirdrops: AirdropOpportunity[] = [
  { id: 'air-001', project_name: 'Monad', category: 'Layer 1', chain: 'Monad', status: 'ACTIVE_CAMPAIGN', official_confirmation: false, website: 'https://monad.xyz', source_url: 'https://monad.xyz/blog', social_url: 'https://x.com/monad_xyz', campaign_url: 'https://monad.xyz/testnet', start_date: hrs(720), requirements: ['Connect wallet', 'Deploy smart contract on testnet', 'Complete testnet transactions'], estimated_effort: 'Medium', opportunity_score: 92, risk_score: 25, confidence_score: 78, funding: '$225M', backers: ['Paradigm', 'Dragonfly Capital', 'Electric Capital'], participants: 850000, token_confirmed: false, tvl: '$12M (testnet)', project_age: '18 months', sybil_risk: 'Medium', scam_risk: 'Low', is_demo: true },
  { id: 'air-002', project_name: 'Berachain', category: 'Layer 1', chain: 'Berachain', status: 'CONFIRMED_AIRDROP', official_confirmation: true, website: 'https://berachain.com', source_url: 'https://berachain.com/airdrop', start_date: hrs(48), end_date: hrs(480), requirements: ['Hold BGT', 'Provide liquidity on BEX', 'Participate in governance'], estimated_effort: 'Low', opportunity_score: 88, risk_score: 15, confidence_score: 95, funding: '$42M', backers: ['Polychain Capital', 'Halcyon Ventures'], participants: 320000, token_confirmed: true, tvl: '$890M', project_age: '2 years', sybil_risk: 'Low', scam_risk: 'Low', is_demo: true },
  { id: 'air-003', project_name: 'EigenLayer', category: 'DeFi', chain: 'Ethereum', status: 'ACTIVE_CAMPAIGN', official_confirmation: true, website: 'https://eigenlayer.xyz', source_url: 'https://eigenlayer.xyz/staking', start_date: hrs(1440), requirements: ['Restake ETH or LSTs', 'Delegate to active operator', 'Maintain restaking position'], estimated_effort: 'Low', opportunity_score: 85, risk_score: 20, confidence_score: 90, funding: '$100M+', backers: ['a16z', 'Polychain Capital', 'Coinbase Ventures'], participants: 450000, token_confirmed: true, tvl: '$14.2B', project_age: '2.5 years', sybil_risk: 'Low', scam_risk: 'Low', is_demo: true },
  { id: 'air-004', project_name: 'Sui Name Service', category: 'Infrastructure', chain: 'Sui', status: 'POTENTIAL_AIRDROP', official_confirmation: false, website: 'https://suins.io', source_url: 'https://suins.io/blog', requirements: ['Register .sui domain', 'Maintain registration', 'Participate in governance'], estimated_effort: 'Low', opportunity_score: 72, risk_score: 30, confidence_score: 55, funding: 'Undisclosed', participants: 120000, token_confirmed: false, project_age: '1 year', sybil_risk: 'Medium', scam_risk: 'Low', is_demo: true },
  { id: 'air-005', project_name: 'Hyperlane', category: 'Infrastructure', chain: 'Multi-chain', status: 'ACTIVE_CAMPAIGN', official_confirmation: true, website: 'https://hyperlane.xyz', source_url: 'https://hyperlane.xyz/blog', start_date: hrs(360), requirements: ['Bridge assets using Hyperlane Warp Route', 'Deploy on testnet', 'Report bugs'], estimated_effort: 'Medium', opportunity_score: 79, risk_score: 22, confidence_score: 82, funding: '$18.5M', backers: ['Variant Fund', 'Galaxy Digital', 'CoinFund'], participants: 65000, token_confirmed: false, project_age: '1.5 years', sybil_risk: 'Low', scam_risk: 'Low', is_demo: true },
  { id: 'air-006', project_name: 'FakeToken Airdrop', category: 'DeFi', chain: 'Ethereum', status: 'SPECULATIVE', official_confirmation: false, website: 'https://faketoken-airdrop.xyz', source_url: 'https://x.com/fake_airdrop', requirements: ['Connect wallet', 'Approve token spending', 'Sign transaction'], estimated_effort: 'Low', opportunity_score: 12, risk_score: 95, confidence_score: 8, participants: 200, token_confirmed: false, project_age: '2 days', sybil_risk: 'High', scam_risk: 'High', risk_flags: ['Newly created domain (2 days old)', 'Requests unlimited token approval', 'No team information', 'Unrealistic reward promises', 'Impersonates legitimate project', 'Suspicious contract interactions'], notes: 'SCAM WARNING: This is a phishing site impersonating a legitimate airdrop.', is_demo: true },
  { id: 'air-007', project_name: 'Jupiter', category: 'DeFi', chain: 'Solana', status: 'ACTIVE_CAMPAIGN', official_confirmation: true, website: 'https://jup.ag', source_url: 'https://jup.ag/launchpad', start_date: hrs(240), requirements: ['Swap on Jupiter', 'Provide LP', 'Vote in governance', 'Use Jupiter Perps'], estimated_effort: 'Low', opportunity_score: 82, risk_score: 12, confidence_score: 88, funding: 'Self-funded', backers: ['ParaFi Capital', 'Republic Capital'], participants: 780000, token_confirmed: true, tvl: '$1.8B', project_age: '3 years', sybil_risk: 'Low', scam_risk: 'Low', is_demo: true },
]

export const demoAlerts: Alert[] = [
  { id: 'alert-001', title: 'CRITICAL: Fed Signals Policy Shift', message: 'Fed Chair indicates preparedness to cut rates in September. Markets now pricing 78% probability of 25bp cut.', priority: 'CRITICAL', asset: 'USD', impact_score: 94, confidence_score: 96, event_id: 'evt-001', source_url: 'https://federalreserve.gov/newsevents', is_read: false, is_dismissed: false, is_demo: true, created_at: mins(12) },
  { id: 'alert-002', title: 'HIGH: Bitcoin Breaks $120K', message: 'BTC surges past $120K resistance with $2.4B in liquidations.', priority: 'HIGH', asset: 'BTC', impact_score: 88, confidence_score: 92, event_id: 'evt-002', source_url: 'https://coinglass.com', is_read: false, is_dismissed: false, is_demo: true, created_at: mins(8) },
  { id: 'alert-003', title: 'IMPORTANT: DeFi Vulnerability Detected', message: 'Security researchers found potential reentrancy vulnerability in major DeFi lending protocol.', priority: 'IMPORTANT', asset: 'DeFi', impact_score: 81, confidence_score: 72, event_id: 'evt-011', is_read: false, is_dismissed: false, is_demo: true, created_at: mins(15) },
  { id: 'alert-004', title: 'HIGH: OPEC+ Emergency Meeting', message: 'OPEC+ calls emergency meeting to discuss 1.5M bpd production cut.', priority: 'HIGH', asset: 'Brent', impact_score: 72, confidence_score: 75, event_id: 'evt-008', is_read: true, is_dismissed: false, is_demo: true, created_at: hrs(1) },
  { id: 'alert-005', title: 'IMPORTANT: Hot US CPI Data', message: 'US August CPI at 3.8% YoY vs 3.5% expected. Core CPI at 3.9%.', priority: 'IMPORTANT', asset: 'USD', impact_score: 85, confidence_score: 98, event_id: 'evt-009', is_read: true, is_dismissed: false, is_demo: true, created_at: hrs(4) },
]

export const demoWatchlist: WatchlistItem[] = [
  { id: 'w-001', symbol: 'BTC', name: 'Bitcoin', asset_class: 'CRYPTO', is_default: true, sort_order: 0, price: 121450, change_24h: 3.2 },
  { id: 'w-002', symbol: 'ETH', name: 'Ethereum', asset_class: 'CRYPTO', is_default: true, sort_order: 1, price: 4820, change_24h: 5.2 },
  { id: 'w-003', symbol: 'SOL', name: 'Solana', asset_class: 'CRYPTO', is_default: true, sort_order: 2, price: 245, change_24h: 4.8 },
  { id: 'w-004', symbol: 'Gold', name: 'Gold (XAU/USD)', asset_class: 'COMMODITIES', is_default: true, sort_order: 3, price: 2580, change_24h: 1.8 },
  { id: 'w-005', symbol: 'Silver', name: 'Silver (XAG/USD)', asset_class: 'COMMODITIES', is_default: true, sort_order: 4, price: 31.2, change_24h: 0.9 },
  { id: 'w-006', symbol: 'WTI', name: 'Crude Oil (WTI)', asset_class: 'COMMODITIES', is_default: true, sort_order: 5, price: 78.5, change_24h: 2.8 },
  { id: 'w-007', symbol: 'EUR/USD', name: 'Euro/Dollar', asset_class: 'FOREX', is_default: true, sort_order: 6, price: 1.0842, change_24h: -0.3 },
  { id: 'w-008', symbol: 'USD/JPY', name: 'Dollar/Yen', asset_class: 'FOREX', is_default: true, sort_order: 7, price: 148.2, change_24h: -0.8 },
  { id: 'w-009', symbol: 'GBP/USD', name: 'Pound/Dollar', asset_class: 'FOREX', is_default: true, sort_order: 8, price: 1.272, change_24h: 0.1 },
  { id: 'w-010', symbol: 'Nasdaq', name: 'Nasdaq 100', asset_class: 'STOCKS', is_default: true, sort_order: 9, price: 20450, change_24h: 1.1 },
  { id: 'w-011', symbol: 'S&P 500', name: 'S&P 500', asset_class: 'STOCKS', is_default: true, sort_order: 10, price: 5620, change_24h: 0.7 },
  { id: 'w-012', symbol: 'DXY', name: 'US Dollar Index', asset_class: 'FOREX', is_default: true, sort_order: 11, price: 103.2, change_24h: -0.4 },
]

export const demoSources: SourceInfo[] = [
  { id: 'src-001', name: 'Federal Reserve', source_type: 'central_bank', credibility: 98, is_active: true, last_scan: mins(5), events_count: 45, accuracy_rate: 99 },
  { id: 'src-002', name: 'Reuters', source_type: 'financial_media', credibility: 92, is_active: true, last_scan: mins(2), events_count: 342, accuracy_rate: 95 },
  { id: 'src-003', name: 'Bloomberg', source_type: 'financial_media', credibility: 93, is_active: true, last_scan: mins(1), events_count: 298, accuracy_rate: 96 },
  { id: 'src-004', name: 'CoinDesk', source_type: 'crypto_media', credibility: 78, is_active: true, last_scan: mins(3), events_count: 187, accuracy_rate: 88 },
  { id: 'src-005', name: 'CoinGlass', source_type: 'crypto_media', credibility: 85, is_active: true, last_scan: mins(1), events_count: 156, accuracy_rate: 92 },
  { id: 'src-006', name: 'Bureau of Labor Statistics', source_type: 'government', credibility: 98, is_active: true, last_scan: hrs(4), events_count: 24, accuracy_rate: 100 },
  { id: 'src-007', name: 'European Commission', source_type: 'government', credibility: 95, is_active: true, last_scan: mins(40), events_count: 18, accuracy_rate: 98 },
  { id: 'src-008', name: 'Crypto Twitter', source_type: 'social', credibility: 30, is_active: true, last_scan: mins(1), events_count: 89, accuracy_rate: 45 },
  { id: 'src-009', name: 'SlowMist Security', source_type: 'crypto_media', credibility: 82, is_active: true, last_scan: mins(10), events_count: 34, accuracy_rate: 91 },
  { id: 'src-010', name: 'CNBC', source_type: 'financial_media', credibility: 85, is_active: true, last_scan: mins(5), events_count: 210, accuracy_rate: 90 },
]

export const demoMarketMovers: MarketMover[] = [
  { symbol: 'BTC', name: 'Bitcoin', price: 121450, change_24h: 3.2, asset_class: 'CRYPTO' },
  { symbol: 'ETH', name: 'Ethereum', price: 4820, change_24h: 5.2, asset_class: 'CRYPTO' },
  { symbol: 'SOL', name: 'Solana', price: 245, change_24h: 4.8, asset_class: 'CRYPTO' },
  { symbol: 'Gold', name: 'Gold', price: 2580, change_24h: 1.8, asset_class: 'COMMODITIES' },
  { symbol: 'WTI', name: 'Crude Oil', price: 78.5, change_24h: 2.8, asset_class: 'COMMODITIES' },
  { symbol: 'DXY', name: 'Dollar Index', price: 103.2, change_24h: -0.4, asset_class: 'FOREX' },
  { symbol: 'EUR/USD', name: 'Euro/Dollar', price: 1.0842, change_24h: -0.3, asset_class: 'FOREX' },
  { symbol: 'USD/JPY', name: 'Dollar/Yen', price: 148.2, change_24h: -0.8, asset_class: 'FOREX' },
  { symbol: 'Nasdaq', name: 'Nasdaq 100', price: 20450, change_24h: 1.1, asset_class: 'STOCKS' },
  { symbol: 'S&P 500', name: 'S&P 500', price: 5620, change_24h: 0.7, asset_class: 'STOCKS' },
]

export const demoMacroCalendar: MacroEvent[] = [
  { id: 'mc-001', date: '2026-08-25', time: '08:30', event: 'US Durable Goods Orders', country: 'US', impact: 'medium', previous: '1.2%', forecast: '0.8%' },
  { id: 'mc-002', date: '2026-08-26', time: '10:00', event: 'US Consumer Confidence', country: 'US', impact: 'high', previous: '102.4', forecast: '100.8' },
  { id: 'mc-003', date: '2026-08-27', time: '02:00', event: 'BOJ Meeting Minutes', country: 'JP', impact: 'high' },
  { id: 'mc-004', date: '2026-08-28', time: '07:00', event: 'German GfK Consumer Confidence', country: 'DE', impact: 'medium', previous: '-21.5', forecast: '-20.0' },
  { id: 'mc-005', date: '2026-08-29', time: '08:30', event: 'US GDP (Q2 Final)', country: 'US', impact: 'high', previous: '2.1%', forecast: '2.1%' },
  { id: 'mc-006', date: '2026-08-29', time: '08:30', event: 'US Core PCE Price Index', country: 'US', impact: 'high', previous: '2.6%', forecast: '2.5%' },
  { id: 'mc-007', date: '2026-09-01', time: '10:00', event: 'US ISM Manufacturing PMI', country: 'US', impact: 'high', previous: '48.5', forecast: '49.0' },
  { id: 'mc-008', date: '2026-09-02', time: '03:45', event: 'RBA Interest Rate Decision', country: 'AU', impact: 'high', previous: '4.10%', forecast: '4.10%' },
]

export const demoSystemStatus: SystemStatus = {
  agents_online: 7, agents_total: 8, sources_online: 9, sources_offline: 1, events_processed: 1247, duplicates_removed: 389, alerts_generated: 45, airdrops_discovered: 23, opportunities_verified: 12, queue_status: 'processing', database_status: 'healthy', last_scan: mins(2),
}

export const demoSettings: UserSettings = {
  notifications_enabled: true, high_impact_threshold: 70, critical_threshold: 90, airdrop_threshold: 70, min_confidence: 60, watched_assets: ['BTC', 'ETH', 'SOL', 'Gold', 'EUR/USD'], watched_sectors: ['Crypto', 'Macro', 'Forex'], quiet_hours_start: '23:00', quiet_hours_end: '07:00', push_enabled: true, email_enabled: false, sound_enabled: true, theme: 'dark',
}